[package]
name = "fileserver"
version = "0.1.0"
authors = ["Matt Fisher <matt.fisher@microsoft.com"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wascc-actor = "0.6"
wascc-codec = "0.6"

[profile.release]
opt-level = "s"

[workspace]
