[package]
name = "oci-distribution"
version = "0.1.0"
authors = [
    "Matt Butcher <matt.butcher@microsoft.com>",
    "Matthew Fisher <matt.fisher@microsoft.com>",
    "Radu Matei <radu.matei@microsoft.com>",
    "Taylor Thomas <taylor.thomas@microsoft.com>",
    "Brian Ketelsen <Brian.Ketelsen@microsoft.com>",
    "Brian Hardock <Brian.Hardock@microsoft.com>",
    "Ryan Levick <rylevick@microsoft.com>",
]
edition = "2018"

[dependencies]
reqwest = { version = "0.10.4", features = ["json"] }
failure = "0.1"
tokio = "0.2.13"
serde = "1.0"
serde_json = "1.0"
www-authenticate = "0.3.0"
hyperx = "0.13"
chrono = { version = "0.4", features = ["serde"] }