apiVersion: v1
kind: Pod
metadata:
  name: greet
spec:
  containers:
    - image: cnabregistry.azurecr.io/wasm:v2
      imagePullPolicy: Always
      name: greet
  nodeSelector:
    kubernetes.io/role: agent
    beta.kubernetes.io/os: linux
    beta.kubernetes.io/arch: wasm32-wasi
