name: Build and Test

on: [pull_request]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              os: "ubuntu-latest",
              url: "https://github.com/casey/just/releases/download/v0.5.8/just-v0.5.8-x86_64-unknown-linux-musl.tar.gz",
              name: "just",
              pathInArchive: "just",
            }
          - {
              os: "macos-latest",
              url: "https://github.com/casey/just/releases/download/v0.5.8/just-v0.5.8-x86_64-apple-darwin.tar.gz",
              name: "just",
              pathInArchive: "just",
            }
    steps:
      - uses: actions/checkout@v2
      - uses: engineerd/configurator@v0.0.1
        with:
          name: ${{ matrix.config.name }}
          url: ${{ matrix.config.url }}
          pathInArchive: ${{ matrix.config.pathInArchive }}
      - name: Build
        run: |
          just build
          just test
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: engineerd/setup-kind@v0.3.0
      - uses: engineerd/configurator@v0.0.1
        with:
          name: just
          url: https://github.com/casey/just/releases/download/v0.5.8/just-v0.5.8-x86_64-unknown-linux-musl.tar.gz
          pathInArchive: just
      - name: Run e2e tests
        env:
          KRUSTLET_NODE_IP: "172.17.0.1"
          # The default location for the cert is not accessible on build hosts, so do it in the current dir
          KEY_DIR: "./config"
          PFX_PASSWORD: "testing"
        run: |
          just bootstrap-ssl
          just build
          cd crates/wascc-provider
          ../../target/debug/krustlet-wascc --node-name krustlet-wascc --port 3000 --pfx-path ../../config/certificate.pfx &
          cd ../wasi-provider
          ../../target/debug/krustlet-wasi --node-name krustlet-wasi --port 3001 --pfx-path ../../config/certificate.pfx &
          just test-e2e
