name: Lint Documentation
on:
  push:
    paths: 'docs/**'
    branches:
      - main
  pull_request:
    paths: 'docs/**'
jobs:
  lint_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: engineerd/configurator@v0.0.5
        with:
          name: just
          url: https://github.com/casey/just/releases/download/v0.5.11/just-v0.5.11-x86_64-unknown-linux-musl.tar.gz
          pathInArchive: just
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install markdownlint
        run: npm install -g markdownlint-cli
      - name: Install markdown-link-check
        run: npm install -g markdown-link-check
      - name: markdownlint
        run: just lint-docs
      - name: markdown-link-check
        run: just linkcheck-docs
